name: DNSrecon CI

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
jobs:
  Python:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12, 3.13, 3.14]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install uv
      uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Lint with ruff
      run: |
        uv run ruff check --fix

    - name: Format with ruff
      run: |
        uv run ruff format

    - name: Commit changes for ruff formating and linting
      if: github.event_name == 'push'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Apply ruff fixes and formatting" || true # Use || true to prevent failure if no changes
        git push origin HEAD:${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Test with pytest
      run: |
        uv run pytest
